version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      MONGO_INITDB_DATABASE: TodoDb
    ports:
      - "27017:27017"
    volumes:
      - ~/todo-app/mongodb:/data/db
      - ./extras/mongoSetup.js:/docker-entrypoint-initdb.d/mongoSetup.js
    networks:
      - mongodb_network
  server:
    container_name: todo-app-server
    build: ./server
    ports:
      - "5000:80"
    networks:
      - mongodb_network
      - app_network
networks:
  mongodb_network:
    name: mongodb_network
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  app_network:
    name: app_network
