version: "3.9"
services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    environment:
      MONGO_INITDB_DATABASE: TodoDb
    ports:
      - "27018:27017"
    volumes:
      - ~/todo-app-db:/data/db
      - ./Extras/:/docker-entrypoint-initdb.d/
  todo-server:
    container_name: todo_server
    build: .
    ports:
      - "50001:443"
      - "50000:80"
    networks:
      - todo_app_network
    extra_hosts:
      host.docker.internal: host-gateway
networks:
  todo_app_network:
    name: todo_app_network
